# Generated by Django 5.2.1 on 2025-05-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus_app', '0003_alter_customuser_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('duration', models.DurationField()),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('Available_date', models.DateField(null=True)),
            ],
        ),
    ]
