# Generated by Django 5.2.1 on 2025-05-21 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus_app', '0004_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bus_No', models.CharField(max_length=50, unique=True)),
                ('Operator_name', models.CharField(max_length=100)),
                ('Bus_image', models.ImageField(blank=True, null=True, upload_to='static/bus_images')),
                ('Bus_Types', models.CharField(choices=[('SEATER', 'SEATER'), ('SLEEPER', 'SLEEPER'), ('AC', 'AC'), ('NONAC', 'NONAC')], max_length=20)),
                ('Seat_No', models.CharField(max_length=10)),
                ('Total_seat', models.IntegerField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Route_Fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bus_app.route')),
            ],
        ),
    ]
