# Generated by Django 5.2.1 on 2025-05-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus_app', '0005_bus_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus_model',
            name='Bus_image',
            field=models.ImageField(blank=True, null=True, upload_to='bus_images'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Profile_Photo'),
        ),
    ]
