# Generated by Django 5.2.1 on 2025-05-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus_app', '0006_alter_bus_model_bus_image_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
