# Generated by Django 5.2.1 on 2025-06-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus_app', '0007_alter_route_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus_model',
            name='Bus_image',
            field=models.ImageField(blank=True, default='bus_images/default.jpg', null=True, upload_to='bus_images'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='profile_images/default.jpg', null=True, upload_to='Profile_Photo'),
        ),
    ]
