# Generated by Django 5.2.1 on 2025-06-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus_app', '0008_alter_bus_model_bus_image_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus_model',
            name='Seat_No',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
