# Generated by Django 5.2.1 on 2025-06-16 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus_app', '0009_alter_bus_model_seat_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus_BookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('site_no', models.CharField(max_length=50)),
                ('passengers', models.CharField(max_length=50)),
                ('bus_Fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bus_app.bus_model')),
                ('user_Fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
