# Generated by Django 5.2.1 on 2025-06-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus_app', '0010_bus_bookingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus_model',
            name='available_seates',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
