# Generated by Django 5.2.1 on 2025-06-16 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bus_app', '0011_bus_model_available_seates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus_bookingmodel',
            old_name='site_no',
            new_name='seat_no',
        ),
    ]
