# Generated by Django 5.2.1 on 2025-06-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus_app', '0012_rename_site_no_bus_bookingmodel_seat_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus_bookingmodel',
            name='total_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
